### ISSUE TITLE
What's the unity of mu times thickness.

### ISSUE THREAD

**Issue by ZeliangSu** [mdw771/xecat#2]
Hi,
It seems that the XrayLib.CS_total_P returns cm2/g which times thickness gives cm3/g. I was expecting something um-1 or m-1 in order to have no unity in the exp(mu * t)?. Am I making a mistake? Thanks

**Comment by mdw771** [comment]
XrayLib.CS_total_P gives the scattering cross section (`sigma`), which is related to the attenuation coefficient (`mu`) by 
`mu = sigma * sample_density`.

**Comment by ZeliangSu** [comment]
Thanks
